[workspace]
resolver = "2"
members = [
    "dace",
    "dace_tests",
    "stack_alg_sim",
    "hist",
    "static_rd",
    "list_serializable",
    "polybenchrun",
    "stack_test_cases",
    "benches/lruvec_bench",
    "benches/stack_alg_sim_bench",
    "static_ri",
    "clam_trace_gen",
    "lease_impl"]

[profile.release]
debug = true
lto = true
